"""init_all_tables

Revision ID: 424d9591d028
Revises: 
Create Date: 2026-04-29 11:38:45.831785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '424d9591d028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_type', sa.String(length=30), nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_id'), 'agent_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_logs_task_id'), 'agent_logs', ['task_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('signal_type', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_return_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_return_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_return_90d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('result_detail', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_task_id'), 'backtest_results', ['task_id'], unique=False)
    op.create_table('chain_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_detail', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'score_date', name='uq_chain_scores_chain_id_score_date')
    )
    op.create_index(op.f('ix_chain_scores_chain_id'), 'chain_scores', ['chain_id'], unique=False)
    op.create_index('ix_chain_scores_chain_id_score_date', 'chain_scores', ['chain_id', 'score_date'], unique=False)
    op.create_table('collect_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collect_logs_source'), 'collect_logs', ['source'], unique=False)
    op.create_table('daily_klines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uq_daily_klines_code_date')
    )
    op.create_index(op.f('ix_daily_klines_code'), 'daily_klines', ['code'], unique=False)
    op.create_index('ix_daily_klines_code_date', 'daily_klines', ['code', 'trade_date'], unique=False)
    op.create_index(op.f('ix_daily_klines_trade_date'), 'daily_klines', ['trade_date'], unique=False)
    op.create_table('financial_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('revenue_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('net_profit_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'report_date', name='uq_financial_reports_code_report_date')
    )
    op.create_index(op.f('ix_financial_reports_code'), 'financial_reports', ['code'], unique=False)
    op.create_index('ix_financial_reports_code_report_date', 'financial_reports', ['code', 'report_date'], unique=False)
    op.create_table('fund_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('north_buy', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('north_sell', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('north_net', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', name='uq_fund_flows_trade_date')
    )
    op.create_index(op.f('ix_fund_flows_trade_date'), 'fund_flows', ['trade_date'], unique=False)
    op.create_table('shareholder_counts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('holder_count', sa.Integer(), nullable=True),
    sa.Column('holder_count_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_holding', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'end_date', name='uq_shareholder_counts_code_end_date')
    )
    op.create_index(op.f('ix_shareholder_counts_code'), 'shareholder_counts', ['code'], unique=False)
    op.create_index('ix_shareholder_counts_code_end_date', 'shareholder_counts', ['code', 'end_date'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=True),
    sa.Column('chain_id', sa.String(length=50), nullable=True),
    sa.Column('source_entity', sa.String(length=100), nullable=True),
    sa.Column('target_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('strength', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('raw_data_ref', sa.String(length=200), nullable=True),
    sa.Column('trigger_date', sa.DateTime(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_chain_id'), 'signals', ['chain_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('stock_fund_flows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('buy_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('sell_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_fund_flows_code'), 'stock_fund_flows', ['code'], unique=False)
    op.create_index(op.f('ix_stock_fund_flows_trade_date'), 'stock_fund_flows', ['trade_date'], unique=False)
    op.create_table('stocks',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_stocks_industry', 'stocks', ['industry'], unique=False)
    op.create_index('ix_stocks_market', 'stocks', ['market'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('macd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('kdj_k', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kdj_j', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_6', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_12', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi_24', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('boll_upper', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('boll_mid', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('boll_lower', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uq_technical_indicators_code_date')
    )
    op.create_index(op.f('ix_technical_indicators_code'), 'technical_indicators', ['code'], unique=False)
    op.create_index('ix_technical_indicators_code_date', 'technical_indicators', ['code', 'trade_date'], unique=False)
    op.create_index(op.f('ix_technical_indicators_trade_date'), 'technical_indicators', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_indicators_trade_date'), table_name='technical_indicators')
    op.drop_index('ix_technical_indicators_code_date', table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_code'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('ix_stocks_market', table_name='stocks')
    op.drop_index('ix_stocks_industry', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_stock_fund_flows_trade_date'), table_name='stock_fund_flows')
    op.drop_index(op.f('ix_stock_fund_flows_code'), table_name='stock_fund_flows')
    op.drop_table('stock_fund_flows')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_chain_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_shareholder_counts_code_end_date', table_name='shareholder_counts')
    op.drop_index(op.f('ix_shareholder_counts_code'), table_name='shareholder_counts')
    op.drop_table('shareholder_counts')
    op.drop_index(op.f('ix_fund_flows_trade_date'), table_name='fund_flows')
    op.drop_table('fund_flows')
    op.drop_index('ix_financial_reports_code_report_date', table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_code'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_daily_klines_trade_date'), table_name='daily_klines')
    op.drop_index('ix_daily_klines_code_date', table_name='daily_klines')
    op.drop_index(op.f('ix_daily_klines_code'), table_name='daily_klines')
    op.drop_table('daily_klines')
    op.drop_index(op.f('ix_collect_logs_source'), table_name='collect_logs')
    op.drop_table('collect_logs')
    op.drop_index('ix_chain_scores_chain_id_score_date', table_name='chain_scores')
    op.drop_index(op.f('ix_chain_scores_chain_id'), table_name='chain_scores')
    op.drop_table('chain_scores')
    op.drop_index(op.f('ix_backtest_results_task_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_agent_logs_task_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
