"""add_eod_screener_tables

Revision ID: b75bebde1c4c
Revises: b5d2e9f14a73
Create Date: 2026-05-09 11:42:59.408854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b75bebde1c4c'
down_revision: Union[str, None] = 'b5d2e9f14a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_backtest_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_loss_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('config_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result_detail', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_backtest_results_task_id'), 'eod_backtest_results', ['task_id'], unique=False)
    op.create_table('eod_screen_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('late_strength', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('signal_strength', sa.String(length=10), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uq_eod_screen_results_code_date')
    )
    op.create_index(op.f('ix_eod_screen_results_code'), 'eod_screen_results', ['code'], unique=False)
    op.create_index('ix_eod_screen_results_date_score', 'eod_screen_results', ['trade_date', 'score'], unique=False)
    op.create_index(op.f('ix_eod_screen_results_trade_date'), 'eod_screen_results', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eod_screen_results_trade_date'), table_name='eod_screen_results')
    op.drop_index('ix_eod_screen_results_date_score', table_name='eod_screen_results')
    op.drop_index(op.f('ix_eod_screen_results_code'), table_name='eod_screen_results')
    op.drop_table('eod_screen_results')
    op.drop_index(op.f('ix_eod_backtest_results_task_id'), table_name='eod_backtest_results')
    op.drop_table('eod_backtest_results')
    # ### end Alembic commands ###
